-- 建立 users table (若不存在才建立)
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    wallet_address VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 插入資料，如果 email 已存在則略過
INSERT INTO users (first_name, last_name, email, password, wallet_address)
VALUES (
  'Peter',
  'Chen',
  'test@example.com',
  '$2a$14$wVsaPvJnJJsomWArouWCtusem6S/.Gauq/GjOIEHpyh2DAMmso1wy',
  '0x1deAe8b25D834F31B88058bc137E8e80E54f1F86'
),
(
  'Andy',
  'Lin',
  'test2@example.com',
  '$2a$14$wVsaPvJnJJsomWArouWCtusem6S/.Gauq/GjOIEHpyh2DAMmso1wy',
  '0xA278Aa560B6A1D2ED46F7faf724C67E9eF20B2EA'
)
ON CONFLICT (email) DO NOTHING;

-- 建立 nft table (若不存在才建立)
CREATE TABLE IF NOT EXISTS nft (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    description TEXT,
    meta VARCHAR(255),
    image VARCHAR(255),
    demo INT
);

-- 插入資料
INSERT INTO nft
VALUES (
  '0',
  '白鳥愛羅',
  '神越高中二年D班的人氣美少女，長著一頭粉髮以及可愛的外表。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/0.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/0.jpg',
  '1'
),
(
  '1',
  '綾瀨桃',
  '出生於靈媒師家庭的辣妹高中生，暱稱「小桃」，自信、膽大、頑強的超能力少女，就讀於神越高中二年B班。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/1.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/1.jpg',
  '1'
),
(
  '2',
  '高倉健',
  '超自然御宅族，以「鄙人」為第一人稱，就讀於神越高中二年C班。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/2.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/2.jpg',
  '1'
),
(
  '3',
  '高速婆婆',
  '神出鬼沒、在日本各地作亂的近代妖怪，也是厄卡倫最初遇到的妖怪，存在歷史久遠，曾被稱為「百公里婆婆」，對自己的腳程有絕對自信，若賽跑輸給她就會被詛咒。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/3.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/3.jpg',
  '1'
),
(
  '4',
  '圓城寺仁',
  '小桃的初戀，暱稱「寺仁」，轉學到小桃的高中並同班，身強體壯的賣萌男。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/4.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/4.jpg',
  '1'
),
(
  '5',
  '賽伯星人',
  '最初試圖綁架小桃的外星人，來自賽伯星，擁有念動力與基因改造能力。種族只有雄性，需要靠複製技術增加個體，為了找回生殖機能而找人類女性下手。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/5.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/5.jpg',
  '1'
),
(
  '6',
  '高倉健(變身版)',
  '高倉健變身造型，可以使用高速婆婆的力量，進行戰鬥。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/6.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/6.jpg',
  '1'
),
(
  '7',
  '綾瀨星子',
  '擅長結界術的靈媒師，小桃的奶奶，人稱「多多利亞三太」，年輕的外表與實際年齡不符。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/7.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/7.jpg',
  '1'
),
(
  '8',
  '高速婆婆(隱藏版)',
  '高速婆婆盲盒隱藏版，隨機出現。',
  'bafybeiectyzmhyq5mjqvdbk3x2g77zbs7odwdkfqzuyzfpey3bxweirasu/8.json',
  'bafybeicqewn5j2amvj6hskp3mey6uztb44gmfoyyk6qsl2wq3zqwydfzdu/8.jpg',
  '1'
),
(
  '9',
  '盲盒',
  '未開箱前的圖案。',
  'bafkreicnovsrbhko6exqtctuhqyg6nvloulmydgu4onfzpp4uqkm7hxle4',
  'bafkreiek5l646yuqixcqxaeengimuub2jcd3zqywvlty2725ecgyjntq44',
  '0'
)